# Generated by Django 5.2.6 on 2025-09-16 15:54

import image_cropping.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar_crop',
            field=image_cropping.fields.ImageRatioField('avatar', '300x300', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='avatar crop'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=image_cropping.fields.ImageCropField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
