"""
Django settings for tech_bloggers project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DJANGO_DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = os.getenv('DJANGO_ALLOWED_HOSTS', '').split(',') if os.getenv('DJANGO_ALLOWED_HOSTS') else []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django.contrib.sitemaps',
    'taggit',
    'easy_thumbnails',
    'image_cropping',
    'django_bleach',
    'axes',
    'apps.accounts',
    'apps.blog',
    'apps.pages',
    'apps.core',
]

# Image cropping settings
from easy_thumbnails.conf import Settings as thumbnail_settings
THUMBNAIL_PROCESSORS = (
    'image_cropping.thumbnail_processors.crop_corners',
) + thumbnail_settings.THUMBNAIL_PROCESSORS

IMAGE_CROPPING_BACKEND = 'image_cropping.backends.easy_thumbnails.EasyThumbnailsBackend'
IMAGE_CROPPING_BACKEND_PARAMS = {}

# Additional image cropping settings
IMAGE_CROPPING_SIZE_WARNING = True
IMAGE_CROPPING_THUMB_SIZE = (300, 300)
IMAGE_CROPPING_MIN_SIZE = [20, 20]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'axes.middleware.AxesMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'tech_bloggers.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"], # Global templated dir
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'tech_bloggers.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


# Static files (CSS, JS, Images)
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

# Media files (user uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Email configuration
# Default to console backend in development if not provided via env
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND') or (
    'django.core.mail.backends.console.EmailBackend' if DEBUG else None
)
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True').lower() == 'true'
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

# Password reset settings
PASSWORD_RESET_TIMEOUT = 86400  # 24 hours in seconds
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER or 'no-reply@tech-bloggers.local'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Authentication settings
LOGIN_REDIRECT_URL = 'pages:index'
LOGIN_URL = 'accounts:login'

AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Axes configuration: lock after 5 failures for 1 hour, keyed by username+IP
AXES_ENABLED = True
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(hours=1)
AXES_LOCK_OUT_BY_COMBINATION_USER_AND_IP = True
AXES_RESET_ON_SUCCESS = True
# Optional: friendly lockout URL or template
AXES_LOCKOUT_TEMPLATE = 'accounts/lockout.html'
# AXES_LOCKOUT_URL = 'accounts:login'

# Sites framework
SITE_ID = 1

# Logging Configuration
DEV_LOGGING_ENABLED = os.getenv('DEV_LOGGING_ENABLED', 'False').lower() == 'true'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {asctime} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'tech_bloggers.log',
            'formatter': 'verbose',
            'maxBytes': 10485760,  # 10MB
            'backupCount': 5,      # Keep 5 backup files
            'encoding': 'utf-8',
        },
        'null': {
            'class': 'logging.NullHandler',
        },
    },
    'loggers': {
        # Django's default logging
        'django': {
            'handlers': ['console', 'file'] if (not DEBUG or DEV_LOGGING_ENABLED) else ['console', 'null'],
            'level': 'INFO',
        },
        # Our application logging
        'apps': {
            'handlers': ['console', 'file'] if (not DEBUG or DEV_LOGGING_ENABLED) else ['console', 'null'],
            'level': 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
    },
}

# WYSIWYG Editor configuration will be added here in the future

# Bleach Configuration
BLEACH_ALLOWED_TAGS = [
    "p", "br", "hr", "div",       # paragraphs, line breaks, and divs
    "b", "i", "u", "em", "strong", "span",  # inline formatting
    "a",                          # links
    "ul", "ol", "li",             # lists
    "blockquote", "code", "pre",  # quotes & code
    "img",                        # images
    "h1", "h2", "h3",             # headings
    "font",                       # font styling (for font-family, font-size)
    "table", "thead", "tbody", "tr", "th", "td",  # tables
]

BLEACH_ALLOWED_ATTRIBUTES = {
    "a": ["href", "title", "rel", "target"],   # safe link attrs
    "img": ["src", "alt", "title", "width", "height"],  # images with size attributes
    "span": ["style"],                         # allow inline style for span
    "font": ["face", "size", "color", "style"], # font attributes including style
    "p": ["style"],                            # paragraph styling (for line-height, text-align)
    "b": ["style"],                            # bold text with styling
    "i": ["style"],                            # italic text with styling
    "u": ["style"],                            # underlined text with styling
    "em": ["style"],                           # emphasized text with styling
    "strong": ["style"],                       # strong text with styling
    "div": ["style"],                          # div styling (for text-align)
    "table": ["style", "border", "cellpadding", "cellspacing"],  # table attributes
    "td": ["style", "colspan", "rowspan"],     # table cell attributes
    "th": ["style", "colspan", "rowspan"],     # table header attributes
    "code": ["class"],                          # code tags
    "pre": ["class"],                           # pre tags for code blocks
}

# Allow specific CSS styles for formatting
BLEACH_ALLOWED_STYLES = [
    'text-decoration',  # for underline
    'text-align',       # for text alignment
    'border',           # for table borders
    'border-collapse',  # for table styling
    'border-spacing',   # for table spacing
    'padding',          # for table cell padding
    'margin',           # for spacing
    'color',            # for text color
    'background-color', # for background color
    'font-family',      # for font styling
    'font-size',        # for font size
    'font-weight',      # for bold
    'font-style',       # for italic
    'line-height',      # for line spacing
    'width',            # for element width
    'height',           # for element height
]

BLEACH_ALLOWED_PROTOCOLS = ["http", "https", "mailto"]  # disallow javascript:

# Additional Bleach settings
BLEACH_STRIP_TAGS = False  # Don't strip tags, just escape
BLEACH_STRIP_COMMENTS = True  # Strip HTML comments